name: sentiment-analysis-Duolingo
channels:
  - defaults
  - conda-forge  # Required for NLP packages
  - pytorch      # Required for PyTorch CPU build
dependencies:
  - python=3.12.9
  - pandas=2.2.3
  - numpy=2.0.1
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - tqdm=4.67.1
  - praw=7.8.1
  - transformers=4.44.1
  - nltk=3.9.1
  - spacy=3.8.2
  - pillow=11.1.0
  - wordcloud=1.9.4
  - pytorch::pytorch-cpu=2.5.1
  - pip
  - pip:
    - emoji==2.14.1